language: python
python:
- '3.8'
services:
- docker
before_script: pip install docker-compose
script:
- docker-compose run app sh -c "python manage.py test && flake8"
deploy:
  provider: heroku
  user: jrlv16-1
  api_key:
    secure: lgYRZDS1BOUVSf2PxiykF6usJNmisExHp/a99lGaT5w7Kz+qRd8ky1zNXpn0JzUEv6/QU+pSGhEkpdw73zluJFzHxwK6p9zZX8wWggltBm5V9oNlLilXkEBa02z7rirUPB1iqFWBgn9SEqUY+z9HzsrzJJ9wpv8t0SFe9KdE04FTNupLGibDT2+WrnhCidEAFIEezHbBWeAzr6DcQmZdL6SOlk7MyKjMoaKhRGb4unq3S7XOnUfGnCFjkF+qLP69TgfRBFJtsXN8bELDhqfLrpATd4ZoFGbnbwAVBS5VQNgkslL2o2aL0p6uqIAMX/+8+f9B/eDNC6XdV87XfBUBNT3l8AXwHnJA8OxUoZpwlwrHyda2VgQeuXHgUeJiYe55YsiS3Z5vJU7/cus0LM0nf+CZXMpGH/g3Qqefjfvdc/UL7wdzQ+RUZ0lTCsI8dgzwqACbGPtZ/Hd0BLYmktrsPBHDgipwYuNvTljfHn7usU8qN1cg+EDGdsEa4N+sVG8VQN+TY8LvnW0014huesvTE0CyYiY7LAaawTJNG8wVUz1Ew0POilnhlYsAeOokWJajG+kmqUQYs3ITxpXGY/fBV9zBwSFwEQQWuv1LOMc/rCxjBqplsnRI1zTRlgF/ahVfwKzSXRVzV01PK/CD6BKENhSGYwbHUfrKhS65i0ypnSk=
    app: jlrecipe